MesdJasperReportViewerBundle_home:
    pattern:  /
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:home" }

MesdJasperReportViewerBundle_reports_json:
    pattern:  /list/json
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:listJson"}

MesdJasperReportViewerBundle_report_form:
    pattern:  /execute/{reportUri}
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:execute" }
    requirements:
        _method: POST

MesdJasperReportViewerBundle_report_history:
    pattern:  /history
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:history" }

MesdJasperReportVIewerBundle_report_history_single:
    pattern:  /history/{reportUri}
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:history" }

MesdJasperReportViewerBundle_report_history_json:
    pattern:  /historylist
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:reportHistoryJson" }

MesdJasperReportViewerBundle_report_history_single_json:
    pattern:  /historylist/{reportUri}
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:reportHistoryJson" }

MesdJasperReportViewerBundle_display_report_viewer:
    pattern:  /display/{reportUri}
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:reportViewer" }

MesdJasperReportViewerBundle_display_history_report_viewer:
    pattern:  /historydisplay/{reportUri}/{existing}
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:reportViewer" }

MesdJasperReportViewerBundle_display_direct_report_viewer:
    pattern:  /displaydirect/{reportUri}/{direct}
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:reportViewer" }

MesdJasperReportViewerBundle_display_page:
    pattern:  /page/{requestId}/{page}
    defaults: { _controller: "MesdJasperReportViewerBundle:ReportViewer:getPage" }