services:
    mesd.jasper.reportviewer.twig.extension:
        class: Mesd\Jasper\ReportViewerBundle\Twig\Extension\ReportViewerExtension
        tags:
            - { name: twig.extension }

    mesd.jasper.reportviewer.linkhelper:
        class: Mesd\Jasper\ReportViewerBundle\Helper\LinkHelper
        arguments: [ @router ]